NUM_MINERS = None

PROPAGATION_VECTOR_WD = []
MAX_PROPAGATION_DELAY_D = None
NETWORK_CAPABILITY_C = None

VDF_MODULUS_N = None
VDF_PHI = None

VDF_SQUARINGS_PER_ROUND = None
POW_HASHES_PER_ROUND = None

MIN_DELAY_ROUNDS = None
MAX_DELAY_ROUNDS = None
TARGET_BLOCK_HEIGHT = None

POW_MINING_PROBABILITY_PER_HASH = None
POW_DIFFICULTY_PHI = None

LOG_LEVEL = None
